### ISSUE TITLE
Crash related to ninja rope?

### ISSUE THREAD

**Issue by Plurp13** [InfinityRaider/NinjaGear#4] opened 2016-11-15 00:19 UTC
No idea what happened, I was mining, very far from the rope, and mid-breaking a block I crashed. The crash report mentions the ninja rope so...yeah.

http://pastebin.com/rwe5yA0U

**Comment by InfinityRaider** [comment] 2016-11-15 17:10
Oh I know what this is, this is caused by a bug persisting over identical code, where I fixed it in most of my mods but forgot to fix it in another.
This should be fixed with the port to InfinityLib, which comes out as soon as the NinjaGear port to InfinityLib is stable enough to my liking.

Thanks for reporting anyways.

**Closed as completed by InfinityRaider** 2016-11-15 17:10 UTC
Labels: bug

**Comment by Plurp13** [comment] 2016-11-15 18:16
Okie dokie, glad it's a known thing with a hopefully easy fix. ^.^

**Comment by InfinityRaider** [comment] 2016-11-15 19:39
It's already fixed :p

**Comment by Plurp13** [comment] 2016-11-15 21:26
Even better ^.^
